services:
  ai-board:
    build:
      context: .
      dockerfile: Dockerfile
    image: meinya/ai-board:latest
    container_name: ai-board
    restart: unless-stopped
    ports:
      - "8872:3000"
    environment:
      - NODE_ENV=production
      # - OPENAI_ENDPOINTS=[{"name": "Local", "url": "http://host.docker.internal:11434/v1", "key": "ollama", "defaultModel": "llama3"}]
